CREATE TABLE sample(
  id VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
) ENGINE = InnoDB;

SELECT * FROM sample;

CREATE TABLE users
(
  id VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

ALTER TABLE users
  RENAME COLUMN name TO first_name;

ALTER TABLE users
  ADD COLUMN middle_name VARCHAR(100) NULL AFTER first_name;

ALTER TABLE users
  ADD COLUMN last_name VARCHAR(100) NULL AFTER middle_name;
