CREATE TABLE sample(
  id VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
) ENGINE = InnoDB;

SELECT * FROM sample;

CREATE TABLE users
(
  id VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

ALTER TABLE users
  RENAME COLUMN name TO first_name;

ALTER TABLE users
  ADD COLUMN middle_name VARCHAR(100) NULL AFTER first_name;

ALTER TABLE users
  ADD COLUMN last_name VARCHAR(100) NULL AFTER middle_name;

CREATE TABLE user_logs
(
  id INT AUTO_INCREMENT,
  user_id VARCHAR(100) NOT NULL,
  action VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

SELECT * FROM user_logs;

DELETE FROM user_logs;

ALTER TABLE user_logs
  MODIFY created_at BIGINT NOT NULL;

ALTER TABLE user_logs
  MODIFY updated_at BIGINT NOT NULL;

DESC user_logs;
